openvinotoolkit/openvino_tokenizers

.github/workflows/windows.yml, src/CMakeLists.txt
Moved install rules at the end and set component name
=> [CI] Aligned install rules 

src/regex_normalization.cpp, src/regex_normalization.hpp, src/tensorflow_translators.cpp, src/utils.cpp, src/utils.hpp
**Ticket:** 132674
**Description:** Tested by https://github.com/openvinotoolkit/openvino/pull/23113
=> [TF FE][Extensions] Support StaticRegexReplace operation

src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Ticket:** 132695
**Details:** Tested by https://github.com/openvinotoolkit/openvino/pull/23131
=> [TF FE][Extensions] Support StringLower operation

src/tensorflow_translators.cpp
**Description:** Add support of string keys for LookupTableFindV2. Tested by https://github.com/openvinotoolkit/openvino/pull/23197
**Ticket:** 132669
=> [TF FE] Add support of string keys for LookupTableFindV2

src/vocab_encoder.cpp
Now the build fails with class template argument deduction failed
=> Fix build on ubuntu18 arm platform

src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Details:** Support StringSplitV2 operation. Tested by https://github.com/openvinotoolkit/openvino/pull/23282.
**Ticket:** 132671
=> [TF FE] Support StringSplitV2 operation

src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Details:** Support RaggedTensorToTensor operation. Tested by https://github.com/openvinotoolkit/openvino/pull/23335
**Ticket:** 132675
=> [TF FE] Support RaggedTensorToTensor operation

src/CMakeLists.txt
w/a to pass protobuf version check in sentence-piece build
=> [CI] Fix macOS tests

tests/pass_rates.json
=> MERGE 2023: [TESTS] updated pass rate (#77)

tests/pass_rates.json
=> MERGE 2024: [TESTS] updated pass rate (#77)

src/equal_str.cpp
**Details:** The issue leads to failures in TextVectorization for white-space input strings. Tested by https://github.com/openvinotoolkit/openvino/pull/23572.
**Ticket:** 135749
=> Fix corner case with empty string for EqualStr

src/bpe_tokenizer.cpp, src/bpe_tokenizer.hpp, src/regex_normalization.cpp, src/regex_normalization.hpp, src/regex_split.cpp, src/regex_split.hpp, src/sentence_piece.cpp, src/sentence_piece.hpp, src/wordpiece_tokenizer.cpp, src/wordpiece_tokenizer.hpp
CVS-136006
Fix an issue with a cached OpenVINO model usage
=> Update Tokenizer Caching

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/cli.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/str_pack.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, src/fuze.cpp, src/fuze.hpp, src/ov_extension.cpp, src/tokenizer.hpp, src/trie_tokenizer.cpp, src/trie_tokenizer.hpp
=> Fix Vector Init

src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Details:** This conversion is needed for mil-nce model from TF Hub. Tested by https://github.com/openvinotoolkit/openvino/pull/23850
=> [TF FE] Extend RaggedTensorToSparse conversion extension

src/vocab_encoder.cpp, src/vocab_encoder.hpp
=> Add Cache to VocabEncoder

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
Currently, a lot of heavy CUDA libraries are installed
=> Install torch CPU

python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, tests/tokenizers_test.py
=> Cherry-Pick From Master

python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, tests/tokenizers_test.py
Required for GenAI repo, which uses latest released version.
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/109
=> Port qwen eos token to 2024.0

src/ov_extension.cpp, src/string_to_hash_bucket.cpp, src/string_to_hash_bucket.hpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp, src/tokenizer.hpp
**Details:** Needed for several models from TF Hub. Tested by https://github.com/openvinotoolkit/openvino/pull/23946
=> [TF FE] Support StringToHashBucketFast operation

pyproject.toml
related PR - https://github.com/openvinotoolkit/openvino/pull/23890
=> [CI]Changed openvino version 2024.2

src/equal_str.cpp
**Details:** Optimize EqualStr operation
=> [TF FE] Optimize EqualStr operation

src/tensorflow_translators.cpp
**Details:** mil-nce model from TF Hub has int32 values for string keys. Tested by https://github.com/openvinotoolkit/openvino/pull/24138
**Ticket:** TBD
=> [TF FE] Extend support for LookupTableFindV2 with string keys

src/tensorflow_translators.cpp
**Details:** It requires for mil-nce model support from TF Hub. Tested by https://github.com/openvinotoolkit/openvino/pull/24148
**Ticket:** TBD
=> [TF FE] Support StringSplitV2 with positive maxplit attribute

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
Use OV released 2024.1 packages
=> [CI] Use OV released 2024.1 packages

src/CMakeLists.txt
=> [MERGE] [CONDA] Link sentencepiece with external protobuf #132

pyproject.toml
=> [MERGE] [WHEEL] Freeze scikit-build-core version #123

CMakeLists.txt, pyproject.toml
=> Version 2024.1.0.1

pyproject.toml
=> [MERGE][2023.3][WHEEL] Freeze scikit-build-core version #123

src/CMakeLists.txt
=> Fixed tokenizers on Windows

pyproject.toml
Connected changes https://github.com/openvinotoolkit/openvino/pull/24673
=> [CI] Changed openvino version 2024.3

src/CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/156
=> Set cmake policies

src/CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/158
=> Fix usage of protobuf_MODULE_COMPATIBLE

CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/162
=> Build release by default (#162)

src/CMakeLists.txt
See https://github.com/conda-forge/sentencepiece-feedstock/blob/main/recipe/build-lib.bat#L12
=> Fixed conda-forge on Windows

src/CMakeLists.txt
* Fixed conda-forge on Windows
* Set policy CMP0077
=> Fixed conda-forge on Windows (#164)

CMakeLists.txt, pyproject.toml
- updated tokenizers version
- updated ov version (will need to merge it simultaneously with ov changes)
https://github.com/openvinotoolkit/openvino/pull/25520
=> [2024.4.0.0] updated ov and tokenizers versions

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, src/CMakeLists.txt
=> [CI] Fixed Jenkins artifacts

.github/workflows/windows.yml, README.md, src/CMakeLists.txt, src/icu_filter_en.json
Squashed Reduce icud.dll commits
=> Reduce icud.dll

python/openvino_tokenizers/cli.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, src/sentence_piece.cpp, src/sentence_piece.hpp, tests/tokenizers_test.py
=> Add Separate Special Token Handling To Sentencepiece

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, CMakeLists.txt, src/CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/213
=> Conda forge fixes for 2024.3 (#213)

.github/workflows/mac.yml, benchmark/benchmark.py, src/CMakeLists.txt, src/equal_str.cpp, src/utils.cpp, src/vocab_encoder.cpp, src/vocab_encoder.hpp
Reverts openvinotoolkit/openvino_tokenizers#219
Check the possibly breaking change
=> Revert "Ops Optimization"

.github/workflows/mac.yml, benchmark/benchmark.py, src/CMakeLists.txt, src/equal_str.cpp, src/utils.cpp, src/vocab_encoder.cpp, src/vocab_encoder.hpp
This reverts commit 5aeec7e0bdbe3af18083145aa67cd28aa5c0f29d.
=> Revert "Revert "Ops Optimization (#219)" (#222)"

src/CMakeLists.txt, src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Details:** Avoid dependency from TF FE in tokenizers. For this we expanded common FE API in https://github.com/openvinotoolkit/openvino/pull/26131. It should be merged after https://github.com/openvinotoolkit/openvino/pull/26131
**Ticket:** CVS-148101
=> [TF FE][Tokenizers] Avoid dependency from TF FE in tokenizers

src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
**Details:** Avoid extra StringTensorPack and StringTensorUnpack operations in a graph
**Ticket:** 149469
=> [TF FE][Tokenizers] Optimize TF FE extensions

src/CMakeLists.txt
Merged after https://github.com/openvinotoolkit/openvino/pull/26269
=> [Cmake] Usage of explicit openvino::threading

src/CMakeLists.txt, src/case_fold.cpp, src/case_fold.hpp, src/normalize_unicode.cpp, src/normalize_unicode.hpp, src/ov_extension.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp, src/tokenizer.hpp, src/wordpiece_tokenizer.cpp, src/wordpiece_tokenizer.hpp
Required for Android and other platforms where FastTokenizers are not available.
=> Enabled build w/o FastTokenizers

CMakeLists.txt, pyproject.toml
Connected PR https://github.com/openvinotoolkit/openvino/pull/26309
=> Bump product version to 2024.5

README.md
(cherry picked from commit 6336aa3624f45438ca794be9c9b3bdf313eb5e50)
=> Port Build Info From Master

.github/workflows/mac.yml, src/CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino_tokenizers/pull/255
=> Fixed manylinux build (#255)

src/bpe_tokenizer.cpp, src/regex_split.hpp, src/utf8_validate.cpp, src/utils.cpp
Fix various memory issues reported by Coverity static analyzer.
=> fix memory issues

CMakeLists.txt, pyproject.toml
Connected PR https://github.com/openvinotoolkit/openvino/pull/26770
=> Bump OV version to 2024.4.1

benchmark/benchmark.py, python/openvino_tokenizers/constants.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, tests/layer_tests.py, tests/pass_rates.json, tests/tokenizers_test.py
=> Store tokenizer conversion params in rt_info / refactor passing params

src/CMakeLists.txt
See https://github.com/openvinotoolkit/openvino_tokenizers/pull/255
Found via https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1051800&view=logs&jobId=fe7faf59-69bb-5487-b8fd-a35a7bda3a51&j=fe7faf59-69bb-5487-b8fd-a35a7bda3a51&t=6610678e-79db-5ced-d3c4-e5157de7c8b6
=> Fixed copy-paste issue

.github/workflows/linux.yml, .github/workflows/windows.yml
Since we didn't agree on downloading them by default.
=> [GHA] Request wheels from OV provider explicitly

src/bpe_tokenizer.cpp, src/bpe_tokenizer.hpp, src/regex_normalization.cpp
Ticket: CVS-154180
**GLM-4 after fix**
```
Sync:  OV: **841.628 FPS**, HF: 2684.016 FPS, OV/HF: 0.31357040631854627
Async: OV: **5475.915 FPS**, HF: 2684.016 FPS, OV/HF: 2.0401946979428316
```
**GLM-4 on master before fix**
```
Sync:  OV: **788.432 FPS**, HF: 2741.423 FPS, OV/HF: 0.2875995256390193
Async: OV: **5437.117 FPS**, HF: 2741.423 FPS, OV/HF: 1.9833191316196308
```
**Mistral-7B-Instruct-v0.1 on master before fix**
```
BPETokenizer_100         40    **0.358209(!!!)**    0.076430 0.006624   0.372613    0.446339
RegexNormalization_84    40    0.000057    0.000004 0.000040   0.000059    0.000060
RegexNormalization_89    40    0.000034    0.000001 0.000031   0.000035    0.000035
very slow, and segfaulted.
```
**Mistral-7B-Instruct-v0.1 after fix**
```
BPETokenizer_100        800 …
```
=> Improve BPE

src/bpe_tokenizer.cpp, src/bpe_tokenizer.hpp, src/charsmap_normalization.cpp, src/charsmap_normalization.hpp, src/regex_normalization.cpp, src/regex_normalization.hpp, src/regex_split.cpp, src/regex_split.hpp, src/sentence_piece.cpp, src/sentence_piece.hpp, src/trie_tokenizer.cpp, src/trie_tokenizer.hpp, src/vocab_encoder.cpp, src/vocab_encoder.hpp
Just added mutex to critical block where internal values of BPENode are changed.
CVS-152028
=> fix evaluate in concurrent scenario

src/charsmap_normalization.cpp, src/ov_extension.cpp, src/regex_split.cpp, src/sentence_piece.cpp, src/sentence_piece.hpp, src/string_to_hash_bucket.cpp, src/tensorflow_translators.cpp, src/tensorflow_translators.hpp
Regression after https://github.com/openvinotoolkit/openvino_tokenizers/pull/298
Also, dropped re2 linkage as it's removed here https://github.com/openvinotoolkit/openvino_tokenizers/pull/294
=> Build w/l FastTokenizers

CMakeLists.txt, pyproject.toml
https://github.com/openvinotoolkit/openvino/pull/27412
=> Bump OV version 2025.0

python/openvino_tokenizers/cli.py, python/openvino_tokenizers/constants.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, tests/layer_tests.py
=> Utf8 turn on

CMakeLists.txt, pyproject.toml
Connected PR
https://github.com/openvinotoolkit/openvino/pull/27929
=> Bump product version to 2024.6

.github/workflows/linux.yml
Reverted w/a with hardcoded paths #329
=> [MERGE][2024.6]Reverted w/a with hardcoded paths #329

.github/workflows/windows.yml
Same as https://github.com/openvinotoolkit/openvino_tokenizers/commit/f79bccbdeb948ec5e0be38b6751d6b1919487cd4 but for provider call in Windows workflow
=> GitHub workspace w/a in Windows workflow

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py
Support WordLevel model parsing from HF tokenizer
Support empty string splitter from HF tokenizer
Support WordLevel detokenizer
CVS-159903
=> Support BART-G2P Tokenizer

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/str_pack.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, src/regex_split.cpp, src/special_tokens_split.cpp, src/string_tensor_pack.cpp, src/string_tensor_pack.hpp, src/utils.cpp, tests/layer_tests.py
=> Revert "Use opset15 version of Str Pack/Unpack (#351)"

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/str_pack.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, src/regex_split.cpp, src/special_tokens_split.cpp, src/string_tensor_pack.cpp, src/string_tensor_pack.hpp, src/utils.cpp, tests/layer_tests.py
=> Revert "Use opset15 version of Str Pack/Unpack (#351)" (#374)

benchmark/benchmark.py, python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, tests/layer_tests.py
Prevent DeprecationWarnings with OpenVINO nightly
=> Replace openvino.runtime imports with openvino

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/str_pack.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, src/regex_split.cpp, src/special_tokens_split.cpp, src/string_tensor_pack.cpp, src/string_tensor_pack.hpp, src/utils.cpp, tests/layer_tests.py
Reverts openvinotoolkit/openvino_tokenizers#380
It breaks TF FE layer tests https://jira.devtools.intel.com/browse/CVS-160803
=> Revert "Revert "Revert "Use opset15 version of Str Pack/Unpack (#351)""

python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/str_pack.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, src/regex_split.cpp, src/special_tokens_split.cpp, src/string_tensor_pack.cpp, src/string_tensor_pack.hpp, src/utils.cpp, tests/layer_tests.py
Reverts openvinotoolkit/openvino_tokenizers#381
It breaks TF FE tests: https://jira.devtools.intel.com/browse/CVS-160803
=> Revert "Revert "Revert "Use opset15 version of Str Pack/Unpack (#351)"""

benchmark/benchmark.py, python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/utils.py, tests/layer_tests.py
Prevent DeprecationWarnings in 2025.0
PR to master branch: https://github.com/openvinotoolkit/openvino_tokenizers/pull/378
=> Replace openvino.runtime imports with openvino for 2025.0

js/openvino-tokenizers.js, js/tests/openvino-tokenizers.test.js
=> [JS] Fix path to libraries on linux arm

.github/workflows/windows.yml
=> [GHA] Explicitly set VS 2022 version

.github/workflows/linux.yml
=> [GHA] added OV TF tests

cmake/external/icu.cmake
PREPEND introduced in 3.16 only
CVS-161934
=> [ICU] Support cmake < 3.16

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
Overall_Status job is needed to simplify management of mandatory checks
=> [CI] Introduced GHA Overall_Status job

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
ported #392 and switched CI to release 2025.5.0 packages
=> [MERGE][2025.0][GHA] Use OV provider on macOS

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
=> [MERGE][2025.0][CI] Introduced GHA Overall_Status job 

src/CMakeLists.txt, src/charsmap_normalization.cpp, src/normalize_unicode.cpp
Required for conda-forge
See https://github.com/conda-forge/openvino-tokenizers-feedstock/pull/34
=> Fixed compilation with external protobuf / abseil

README.md, python/openvino_tokenizers/tokenizer_pipeline.py
- Support tokenizers from GGUF models
- Add a GGUF model example
- Add Unicode support info
=> Support GGUF, Update README.md

src/CMakeLists.txt
=> [JS] Fix the rpath in the openvino-tokenizer build for npm

.github/workflows/windows.yml, CMakeLists.txt
Ported https://github.com/openvinotoolkit/openvino.genai/pull/1822
=> Allow build w/o python

python/openvino_tokenizers/cli.py
=> Fix CLI Arg Default Value

CMakeLists.txt, pyproject.toml
https://github.com/openvinotoolkit/openvino/pull/29463
=> Bump product version 2025.2

cmake/external/icu.cmake
=> [ICU] Set openvino compile defenitions

src/tensorflow_translators.cpp
This is related to https://github.com/openvinotoolkit/openvino/pull/29339#issuecomment-2720981513
=> Support complex tensors for equal

python/openvino_tokenizers/utils.py
=> Write into rt_info string instead of python enum object.

cmake/external/icu.cmake
Set CL and LINK env to propagate security compilation flags
=> ICU compile flags

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, cmake/external/icu.cmake
Ported the following PRs:
- #440 
- #438
=> [MERGE] Ported compile flags fixes

.github/workflows/linux.yml, .github/workflows/windows.yml
https://github.com/openvinotoolkit/openvino/pull/29635
=> [GHA] Use separate artifacts folder structure

python/openvino_tokenizers/__init__.py
=> Check Binary Compatibility Before Patching

python/openvino_tokenizers/__init__.py
Skip OpenVINO_DIR when it is a build directory, not an installation path.
=> Skip OpenVINO_DIR

js/package-lock.json, js/package.json
=> [JS} Upgrade the js package versions to the upcoming releases

src/bpe_tokenizer.hpp, src/ragged_to_ragged.cpp, src/regex_normalization.cpp, src/regex_split.cpp, src/sentence_piece.cpp, src/special_tokens_split.cpp, src/tensorflow_translators.cpp, src/truncate.cpp, src/utils.cpp, src/utils.hpp, tests/pass_rates.json
CVS-167162
- Fix Sentencepiece input pointers
- Update `pair_inputs` pass rate
=> Fix Coverity Sentencepiece

python/openvino_tokenizers/cli.py
=> add `number_of_inputs` to cli

src/tokenizers_factory.cpp, src/tokenizers_factory.hpp
**Details:** Needed for GGUF tokenizers support to create a computation graph corresponding to tokenizer/detokenizer read from GGU file.
**Ticket:** 166479
=> [GGUF] Create tokenizers factory for GGUF support in OpenVINO GenAI

js/openvino-tokenizers.d.ts, js/package.json
- Add d.ts types for JS package
CVS-168323
=> [JS] Add types for openvino-tokenizers

benchmark/benchmark.py, pyproject.toml, python/openvino_tokenizers/__init__.py, python/openvino_tokenizers/build_tokenizer.py, python/openvino_tokenizers/cli.py, python/openvino_tokenizers/convert_tokenizer.py, python/openvino_tokenizers/hf_parser.py, python/openvino_tokenizers/tiktoken_parser.py, python/openvino_tokenizers/tokenizer_pipeline.py, python/openvino_tokenizers/tokenizer_transformations.py, python/openvino_tokenizers/utils.py, tests/layer_tests.py, tests/tokenizers_test.py
=> Change Typing According to PEP 585

src/tokenizers_factory.cpp
- Is needed for https://github.com/openvinotoolkit/openvino.genai/pull/2457
=> add `Truncate` and `CombneSegments` to node factory

src/ragged_to_dense.cpp, src/ragged_to_dense.hpp, tests/layer_tests.py
- Added optional input for RaggedToDence to sitch padding side on runtime
- Generated IRs are not affected
Ticket: CVS-163374
=> add optional pad_right input to RaggedToDence op

benchmark/benchmark.py, src/bpe_tokenizer.cpp
Replaced count() + at() pattern with single find() calls
~+7% Sync TPUT
=> [BPE] Optimize Lookup

src/CMakeLists.txt, src/regex_split.hpp, src/sentence_piece.cpp, src/sentence_piece.hpp, src/utils.cpp, src/utils.hpp, third-party-programs.txt
Remove the last usage of re2 library. Use pcre2 instead.
Update sentencepiece to 0.2.1.
Update pcre2 to 10.46.
=> Remove re2 Dependency
