openvinotoolkit/openvino_tokenizers

CMakeLists.txt
src/CMakeLists.txt

- Added C++17 support required for ABSL
- Refactor cmake to contain logic sections of build and packaging process

Refactor cmake, added C++17 as required

---

python/openvino_tokenizers/utils.py

The original code generats a list consists of 'Parameter' and 'Output' for remaining_inputs, that causes error on generating a new connected model with Model(outputs, inputs, model_name).
I modified the code to generate a list of 'Parameter'.

Generates list of 'Parameter' instead of 'Output' for remaining_inputs.

---

pyproject.toml

OpenVINO supports 3.12 as well

Update pyproject.toml to reflect support of python 3.12

---

src/tensorflow_translators.cpp
src/tensorflow_translators.hpp

**Details:** TensorFlow uses named output tensors for operations in body graphs

[TF FE] Add named output tensors support for StringSplitV2 operation

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml

Switched release branch to prebuilt openvino packages

[CI] Ported Prebuild openvino packages (#69)

---

src/equal_str.cpp

**Details:** Not needed to allocate vector in case empty bytestream. This PR finally allows layer test to pass on ASCII sequences in PR https://github.com/openvinotoolkit/openvino/pull/23433.

Correct EqualStr in case empty strings

---

pyproject.toml

Jira ticket: 136121
According to https://peps.python.org/pep-0440/#compatible-release 
openvino~=2024.1.0.0.dev (analog >= 2024.1.0.0.devN, == 2024.1.0.*) should suite the both cases:
1) ov == 2024.1.0
2) ov == 2024.1.0.devN

[WHEEL] Support of OV nightly packages

---

pyproject.toml

Like https://github.com/openvinotoolkit/openvino_tokenizers/pull/108 
will be reverted when OV CI switched to the new 2024.3 version

[CI] Temporary removed dependency version of OpenVINO

---

README.md
python/openvino_tokenizers/cli.py
python/openvino_tokenizers/convert_tokenizer.py

Changes made in both CLI and API. API changes will directly affect how optimum-intel converts tokenizers as it doesn't override defaults. Keep old options for the CLI part for backward compatibility.

Switch default skip tokens flag behavior

---

CMakeLists.txt
src/CMakeLists.txt

Compiling GenAI with OpenVINO from sources sets `CMAKE_SKIP_INSTALL_RPATH` to `ON`. I can’t reproduce it for openvino_tokenizers. `RUNPATH` exists in `objdump -x openvino_tokenizers/lib/libopenvino_tokenizers.so | grep 'R.*PATH'` while compiling everything from sources. `RUNPATH` is there in the wheel as well produced by CI. It’s only missing from the archive, which is fine because of setupvars. I can’t find why `RUNPATH` is set for openvino_tokenizers, but forcing `CMAKE_SKIP_INSTALL_RPATH` to `OFF` won’t harm anyway.

Configure cmake similar to GenAI

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
CMakeLists.txt
pyproject.toml

OpenVINO wheels will include cmake configurations and headers (see https://github.com/openvinotoolkit/openvino/pull/25036), after that we would be able to build extensions without downloading of OpenVINO tarballs at all

Support build from OpenVINO wheel only

---

src/CMakeLists.txt

* Configure cmake similar to GenAI
Compiling GenAI with OpenVINO from sources sets `CMAKE_SKIP_INSTALL_RPATH` to `ON`. I can’t reproduce it for openvino_tokenizers. `RUNPATH` exists in `objdump -x openvino_tokenizers/lib/libopenvino_tokenizers.so | grep 'R.*PATH'` while compiling everything from sources. `RUNPATH` is there in the wheel as well produced by CI. It’s only missing from the archive, which is fine because of setupvars. I can’t find why `RUNPATH` is set for openvino_tokenizers, but forcing `CMAKE_SKIP_INSTALL_RPATH` to `OFF` won’t harm anyway.
* option->set, remove needless CMAKE_SKIP_INSTALL_RPATH

Configure cmake similar to GenAI (#175)

---

python/openvino_tokenizers/cli.py
python/openvino_tokenizers/convert_tokenizer.py
python/openvino_tokenizers/hf_parser.py
src/sentence_piece.cpp
src/sentence_piece.hpp
tests/tokenizers_test.py

Add `handle_special_tokens_with_re` to `convert_tokenizer` and `--handle-special-tokens-with-re` flag to CLI. It enables a separate treatment of special tokens in sentencepiece-based tokenizers. Fixes some BPE tokenizers. 
CVS-145609

Add Separate Special Token Handling To Sentencepiece

---

src/utils.cpp
src/utils.hpp

`match_data` contains data unique for inputs string and should be allocated individually for each thread and evaluate instance.
Ticket: CVS-149376

Fix segfault in PCRE2

---

src/utils.cpp

`ovector` in PCRE2 wrapper was pointing to the freed memory location. Need to copy values to results and free only after that.

Fix Segfault on Mac

---

src/regex_split.cpp

When split pattern is empty both RE2 and PCRE2 `get_next_match` return matching `curr_begin` and `curr_end` and enter infinite loop since `start` was not incremented. Need to exit cycle when that happens.

Fix infinite loop in split for empty split_pattern

---

src/utils.cpp

Previous code was written in the assumption that outlengthptr/subject_length is not used and stores only output, but that was incorrect. According to https://www.pcre.org/current/doc/html/pcre2_substitute.html the last argument value is also used during replace. Fixed that.
Ticket: CVS-152028

fix calling PCRE2

---

python/openvino_tokenizers/convert_tokenizer.py
python/openvino_tokenizers/utils.py
tests/tokenizers_test.py

Follow up for CVS-146675. Python <= 3.9 does not have __match_args__, use fields instead.

use fields instead of __match_args__

---

python/openvino_tokenizers/tokenizer_pipeline.py

There was a degradation introduced in https://github.com/openvinotoolkit/openvino_tokenizers/pull/269 
which prevents from upgrading genai to the latest tokenizers https://github.com/openvinotoolkit/openvino.genai/pull/953

fix "Fix Split Mode Names #269" degradation

---

src/regex_normalization.cpp

CVS-155983
Reformat normalization replace pattern to be compatible with PCRE2 for backward compatibility.

Use PCRE2 Compatible Regex Pattern

---

src/CMakeLists.txt

Put binaries at the top level of archive for CPack generator = npm. This needs to get archive with structure for NPM package.
Tasks:
- 157481

[JS] Adopt cmake config for cpack generator = npm

---

python/openvino_tokenizers/cli.py
python/openvino_tokenizers/constants.py
python/openvino_tokenizers/convert_tokenizer.py
python/openvino_tokenizers/hf_parser.py
python/openvino_tokenizers/tokenizer_pipeline.py
python/openvino_tokenizers/utils.py
tests/layer_tests.py

for `TextCallbackStreamer` to handle unfinished characters correctly
https://github.com/openvinotoolkit/openvino.genai/blob/master/src/cpp/src/text_callback_streamer.cpp#L26-L27
CVS-157110

Turn on UTF8Validate.REPLACE by default

---

python/openvino_tokenizers/__init__.py
python/openvino_tokenizers/hf_parser.py

After https://github.com/openvinotoolkit/openvino/pull/27902 creating with _get_node_factory_opset1 has broken. Use _get_factory instead

replace _get_node_factory_opset1 usage with _get_factory

---

pyproject.toml

py-build-cmake incorrectly set python_tag (cpp311), should be py3

[WHEEL] Set python_tag

---

python/openvino_tokenizers/hf_parser.py
python/openvino_tokenizers/tokenizer_pipeline.py

- Fix set `attention_mask` tensor name as model output tensor name.
- When is required that tensor name(s) should be model output tensor names they should be set to Result` node or OV Model output tensor. The OV pre-post-processor for model v11 will not move the tensor names. If tensor names is not assigned to Result then it will be kept on that node when additional layer(s) added between Node and Result.
- openvinotoolkit/openvino.genai#1390

[bug] Fix set tensor name for `attention_mask`

---

python/openvino_tokenizers/constants.py
python/openvino_tokenizers/hf_parser.py
python/openvino_tokenizers/tokenizer_pipeline.py
python/openvino_tokenizers/utils.py

Llama3 missed added tokens since GLM Edge support. Fixed the issue.

Fix Issue With Added Tokens

---

.github/workflows/mac.yml

Switch CI on OV prebuilt package on macOS

[GHA] Use OV provider on macOS

---

js/package-lock.json
js/package.json

- update `openvino-tokenizers-node` package version to 2025.0.0

[JS] Update openvino-tokenizers-node package version to 2025.0.0

---

cmake/external/icu.cmake

- Propagate linker flags for ICU build
- Fix build issue with enabled sanitizer:
```
/usr/bin/ld: ../../lib/libicuuc.a(putil.ao): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```

Propagate linker flags for ICU build

---

src/bytes_to_chars.cpp
src/regex_split.cpp
src/special_tokens_split.cpp
src/utf8_validate.cpp
src/utils.cpp

- Update pointers to tensor data to be constant when tensor is const.
- openvinotoolkit/openvino#29594

Use const pointers for const tensors

---

python/openvino_tokenizers/tokenizer_transformations.py

`openvino.runtime` is deprecated since `openvino 2025.0`.  
https://github.com/openvinotoolkit/openvino_tokenizers/pull/378

Replace openvino.runtime import

---

.github/workflows/coverity.yml

the new version of the coverity util doesn't support --fs-capture-search option

[GHA] removed unused option for the new coverity version
